var target = args[0];
var moneyThresh = getServerMaxMoney(target) * 0.75 //0.05;
var securityThresh = getServerMinSecurityLevel(target) + 5;

while (true) {
	if (getServerSecurityLevel(target) > securityThresh) {
		weaken(target);
		toast(getHostname() + ": Weakened " + target, "info")
	} else if (getServerMoneyAvailable(target) < moneyThresh) {
		grow(target);
		toast(getHostname() + ": Grew " + target, "info")

	} else {
		hack(target);
			toast(getHostname() + ": Hacked " + target)
	}
}